const LS='bogas_catering_v6';
const state=JSON.parse(localStorage.getItem(LS)||'null')||{data:DEFAULT_DATA,offers:[],activeOffer:null,selected:{},req:[],tab:'offer'};
function save(){localStorage.setItem(LS,JSON.stringify(state));}
function $(s){return document.querySelector(s)}
function uid(){return Math.random().toString(36).slice(2,9)}
function nextNo(){const nums=state.offers.map(o=>Number(String(o.no).split('-')[1]||0)); const n=Math.max(state.data.offerStart-1,...nums)+1; return `${state.data.offerYear}-${n}`}
function kg(g){return g>=1000?(g/1000).toFixed(2).replace('.',',')+' kg':Math.round(g)+' g'}
function todayPlus(d){let x=new Date();x.setDate(x.getDate()+d);return x.toLocaleDateString('de-DE')}
function active(){if(!state.activeOffer) newOffer(); return state.offers.find(o=>o.id===state.activeOffer)}
function newOffer(){const o={id:uid(),no:nextNo(),created:new Date().toISOString(),customer:'',eventType:'',persons:50,finalPersons:50,date:'',foodTime:'',pricePerPerson:'',notes:'',positions:[{name:'BBQ Buffet',qty:50,unit:'Pers.',price:''}],selected:{},req:[]}; state.offers.unshift(o); state.activeOffer=o.id; save();}
function selectedCount(catId){const o=active();return Object.values(o.selected[catId]||{}).filter(Boolean).length}
function calcRows(final=true){const o=active(), p=Number(final?o.finalPersons:o.persons)||0, rows=[]; state.data.categories.forEach(cat=>{const c=selectedCount(cat.id)||1; (cat.items||[]).forEach(it=>{if(!(o.selected[cat.id]||{})[it.id])return; if(it.components){it.components.forEach(co=>rows.push({cat:cat.name,item:co.name,amount:kg(co.grams*p),raw:co.grams*p,label:it.name}))} else if(it.portionsByCount){let f=it.portionsByCount[Math.min(c,cat.max)]||0; rows.push({cat:cat.name,item:it.name,amount:Math.ceil(f*p)+' '+(it.unit||'Portionen'),raw:Math.ceil(f*p),label:it.name})} else {let g=it.gramsByCount[Math.min(c,cat.max)]||0; rows.push({cat:cat.name,item:it.name,amount:kg(g*p),raw:g*p,label:it.name})}})}); return rows}
function render(){const o=active(); const app=$('#app'); app.innerHTML=`<div class="wrap"><div class="top"><div><div class="brand">${state.data.company.logoText}</div><div class="muted">Catering Software</div></div><button class="btn" onclick="newOffer();render()">+ Neues Angebot</button></div><div class="tabs">${['offer:Angebot','food:Speisen','work:Arbeitsliste','labels:Etiketten','config:Konfiguration'].map(x=>{let[a,b]=x.split(':');return `<button class="tab ${state.tab==a?'active':''}" onclick="state.tab='${a}';save();render()">${b}</button>`}).join('')}</div>${views[state.tab](o)}</div><div class="actions"><button class="btn" onclick="window.print()">Drucken/PDF</button><button class="btn gold" onclick="downloadCSV()">CSV exportieren</button></div><div id="print" class="printOnly"></div>`; renderPrint();}
const views={offer:o=>`<div class="card"><h2>Angebot ${o.no}</h2><div class="grid"><div><label>Kundenname</label><input value="${o.customer}" oninput="o().customer=this.value;save()"></div><div><label>Art der Veranstaltung</label><input value="${o.eventType}" oninput="o().eventType=this.value;save()"></div><div><label>Personenzahl Angebot</label><input type="number" value="${o.persons}" oninput="o().persons=Number(this.value);o().finalPersons=o().finalPersons||o().persons;save();render()"></div><div><label>Finale Personenzahl für Arbeitslisten</label><input type="number" value="${o.finalPersons}" oninput="o().finalPersons=Number(this.value);save();render()"></div><div><label>Datum Catering</label><input type="date" value="${o.date}" oninput="o().date=this.value;save()"></div><div><label>Essenszeit</label><input type="time" value="${o.foodTime}" oninput="o().foodTime=this.value;save()"></div></div><label>Notizen</label><textarea oninput="o().notes=this.value;save()">${o.notes||''}</textarea></div><div class="card"><h3>Was benötigen wir vor Ort?</h3><div class="chips">${state.data.requirements.map(r=>`<button class="chip ${o.req.includes(r)?'active':''}" onclick="toggleReq('${esc(r)}')">${r}</button>`).join('')}</div></div>`,
food:o=>state.data.categories.map(cat=>`<div class="card"><h2>${cat.name}</h2><p class="muted">${selectedCount(cat.id)} ausgewählt</p><div class="chips">${cat.items.map(it=>`<button class="chip ${(o.selected[cat.id]||{})[it.id]?'active':''}" onclick="toggleFood('${cat.id}','${it.id}')">${it.name}</button>`).join('')}</div></div>`).join(''),
work:o=>`<div class="card"><h2>Küchenliste</h2><p>${o.customer||'Ohne Kunde'} · ${o.finalPersons} Personen final</p><table><tr><th>Kategorie</th><th>Artikel</th><th class="right">Menge</th></tr>${calcRows().map(r=>`<tr><td>${r.cat}</td><td>${r.item}</td><td class="right">${r.amount}</td></tr>`).join('')}</table></div>`,
labels:o=>`<div class="card"><h2>Produktionsetiketten</h2><p class="muted">Beim Drucken/PDF werden Etiketten für alle Komponenten erstellt.</p><div class="labelGrid">${labelHtml(o)}</div></div>`,
config:o=>`<div class="card"><h2>Konfiguration</h2><p class="muted">Diese Version speichert die Speisen lokal im Browser. Für echten Admin-Login/Datenbank ist danach Supabase dran.</p><button class="btn gold" onclick="addItemPrompt()">+ Speise hinzufügen</button> <button class="btn" onclick="exportConfig()">Konfiguration exportieren</button><label>Konfiguration importieren</label><input type="file" onchange="importConfig(this.files[0])"></div>${state.data.categories.map(cat=>`<div class="card"><h3>${cat.name}</h3>${cat.items.map(it=>`<div class="row"><div>${it.name}</div><button class="btn danger" onclick="deleteItem('${cat.id}','${it.id}')">Löschen</button></div>`).join('')}</div>`).join('')}`};
function o(){return active()} function esc(s){return String(s).replaceAll("'","&#39;")}
function toggleReq(r){const a=o().req; a.includes(r)?a.splice(a.indexOf(r),1):a.push(r); save(); render()}
function toggleFood(c,i){o().selected[c]=o().selected[c]||{}; o().selected[c][i]=!o().selected[c][i]; save(); render()}
function labelHtml(o){return calcRows().map(r=>`<div class="label"><b>${state.data.company.logoText}</b><br>Kunde: ${o.customer||'-'}<br>Event: ${o.eventType||'-'}<br>Datum: ${o.date||'-'} · Personen: ${o.finalPersons}<hr><b>${r.item}</b><br>Menge: ${r.amount}</div>`).join('')}
function renderPrint(){const o=active(); $('#print').innerHTML=`<div class="printCard"><h1>${state.data.company.logoText}</h1><h2>Angebot ${o.no}</h2><p><b>Kunde:</b> ${o.customer||'-'}<br><b>Veranstaltung:</b> ${o.eventType||'-'}<br><b>Datum:</b> ${o.date||'-'} · <b>Essenszeit:</b> ${o.foodTime||'-'}<br><b>Personen:</b> ${o.persons}</p><h3>Buffet</h3><ul>${state.data.categories.map(c=>Object.entries(o.selected[c.id]||{}).filter(x=>x[1]).map(([id])=>`<li>${c.items.find(i=>i.id==id)?.name||id}</li>`).join('')).join('')}</ul>${o.req.length?'<h3>Benötigt vor Ort</h3><ul>'+o.req.map(r=>`<li>${r}</li>`).join('')+'</ul>':''}<p>Das Angebot ist bis zum ${todayPlus(14)} gültig.</p><p>Bitte vergessen Sie nicht Ihre Dienstleister, wie zum Beispiel DJ, Fotograf und weitere. Unser Mitarbeiter planen wir, für Sie kostenlos, mit ein.</p><p>Unsere Rechnung können Sie zum Teil unter Haushaltsnahe Dienstleistungen in der Steuererklärung absetzten, da wir alles für Sie vor Ort zubereiten.</p><p>Für Rückfragen stehen wir Ihnen jederzeit gerne zur Verfügung.<br>Wir bedanken uns sehr für Ihr Vertrauen.</p><p>Mit freundlichen Grüßen<br>${state.data.company.signature}</p><p><b>${state.data.company.name}</b><br>${state.data.company.address.replaceAll('\n','<br>')}<br>Tel. ${state.data.company.phone}<br>E-Mail ${state.data.company.email}<br>Web ${state.data.company.web}</p></div><h2>Etiketten</h2><div class="labelGrid">${labelHtml(o)}</div>`}
function downloadCSV(){let csv='Kategorie;Artikel;Menge\n'+calcRows().map(r=>`${r.cat};${r.item};${r.amount}`).join('\n'); const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='Kuechenliste_'+(o().no||'')+'.csv';a.click()}
function addItemPrompt(){const cn=prompt('Kategorie: salate, fleisch, beilagen oder dessert'); const cat=state.data.categories.find(c=>c.id==cn); if(!cat)return alert('Kategorie nicht gefunden'); const name=prompt('Name der Speise'); if(!name)return; const vals=prompt('Gramm/Person nach Anzahl, mit Komma getrennt. Beispiel: 360,180,120,90,60'); const arr=(vals||'').split(',').map(x=>Number(x.trim())).filter(Boolean); const item={id:uid(),name,gramsByCount:{}}; arr.forEach((v,i)=>item.gramsByCount[i+1]=v); cat.items.push(item); save(); render()}
function deleteItem(c,id){const cat=state.data.categories.find(x=>x.id==c); cat.items=cat.items.filter(i=>i.id!=id); save(); render()}
function exportConfig(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'}));a.download='bogas-konfiguration.json';a.click()}
function importConfig(f){const r=new FileReader();r.onload=()=>{state.data=JSON.parse(r.result);save();render()};r.readAsText(f)}
render();
